GET http://localhost:5274/

###
GET http://localhost:5274/api/categories/

###
GET http://localhost:5274/api/categories/5

###
GET http://localhost:5274/api/tags

###
GET http://localhost:5274/api/tags/1

###
GET http://localhost:5274/api/recipes/8

###
GET http://localhost:5274/api/recipes

###
POST http://localhost:5274/api/recipes
Content-Type: application/json

{
    "recipeName": "Chicken Biryani",
    "ingredients": [
        {
            "ingredientName": "Chicken",
            "quantity": 500,
            "unit": "g"
        },
        {
            "ingredientName": "Rice",
            "quantity": 300,
            "unit": "g"
        }
    ],
    "instructions": [
        {
            "stepNumber": 1,
            "description": "Wash the rice."
        },
        {
            "stepNumber": 2,
            "description": "Cook the chicken."
        }
    ],
    "categories": [
        "Main Dishes"
    ],
    "tags": [
        "Indian",
        "Easy"
    ]
}

###
DELETE  http://localhost:5274/api/recipes/8